# input("Enter first num: ")
num1 = input("Enter first num: ")
num2 = input("Enter sec num: ")
print(num1 + num2)
print(type(num1))
print(type(num2))
# we have to do type conversion
# way1
print(int(num1) + int(num2))
# way2
num1 = int(input("Enter first num: "))
num2 = int(input("Enter sec num: "))
print(num1 + num2)
print(type(num1))
print(type(num2))
# float
num3 = (input("Enter decimal:"))
num4 = (input("Enter sec deci: "))
print(num3 + num4)
print(type(num3))
print(type(num4))
print(float(num3) + float(num4))
print(type(num3))
print(type(num4))
num3 = float(input("Enter decimal:"))
num4 = float(input("Enter sec deci: "))
print(type(num3))
print(type(num4))
print(num3 + num4)
